plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

title: Diary of a Differential Teapot
description: Let's explore the world of differential rendering, and more!

# markdown: kramdown
# kramdown:
#   parse_block_html: false

theme: jekyll-theme-midnight